apiVersion: v1
kind: Service
metadata:
  name: miniflux-svc
spec:
  ports:
    - name: web
      port: 43241
      targetPort: 8080
  selector:
    io.kompose.service: miniflux
status:
  loadBalancer: {}
