apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: miniflux
    k8s-app: metrics
  name: miniflux
spec:
  ports:
    - name: web
      port: 43241
      targetPort: 8080
  selector:
    io.kompose.service: miniflux
status:
  loadBalancer: {}
