apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\I337313\Documents\bin\common\kompose.exe convert --out ./kube-artifacts
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: pg
  name: pg
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pg
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\I337313\Documents\bin\common\kompose.exe convert --out
          ./kube-artifacts
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: pg
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: secret
        - name: POSTGRES_USER
          value: miniflux
        image: postgres:latest
        imagePullPolicy: ""
        name: pg
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
