apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: rsshub
  name: rsshub
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rsshub
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.service: rsshub
    spec:
      containers:
        - env:
            - name: LOGGER_LEVEL
              value: warn
            - name: NODE_ENV
              value: production
            - name: PRE_FETCH
              value: "false"
          image: theosun/rsshub:latest
          imagePullPolicy: IfNotPresent
          name: rsshub
          ports:
            - containerPort: 1200
          resources:
            limits:
              cpu: "100m"
              memory: "200M"
      restartPolicy: Always
      serviceAccountName: ""
status: {}
