apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: rsshub
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rsshub
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

