apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\I337313\Documents\bin\common\kompose.exe convert --out ./kube-artifacts
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: rsshub
  name: rsshub
spec:
  ports:
  - name: "1200"
    port: 1200
    targetPort: 1200
  selector:
    io.kompose.service: rsshub
status:
  loadBalancer: {}
